### ISSUE TITLE
To-do-Liste

### ISSUE THREAD

**Issue by Circonflexe** [we-pnp/hero#3]
## Universum
- [x] Wie heißt die Stadt, in der wir spielen? 
  - Nikohara
- [x] Wie heißt die Schule, auf die wir gehen?
  - Misaki High School
- [x] In welcher Klima-Zone Japans liegt unsere fiktive Stadt?
  - gemäßigt mit Jahreszeiten (Schnee im Winter, feuchtwarme Sommer)
- [x] In welchem Monat/welcher Jahreszeit starten wir?
  - 25.08. dh Hochsommer
- [x] Besitzen unsere Charaktere Smartphones?
  - ja
- [x] Wie umfangreich ist unser Zugang zum Internet - sollten/dürfen wir Problemstellungen damit lösen?
  - ja
  - Google = Yahoogle
- [x] Da unsere Charaktere auf eine Internat-Schule gehen - in welcher Form ist Personalisierung der Zimmer durch persönlichen Besitz erlaubt/nicht erlaubt?
  - alles erlaubt
- [x] In wie weit haben unsere Charaktere Zugang zu Geld? Bürgerliche Nebenjobs möglich? Evtl. sogar Jobs innerhalb der Schule? Taschengeld der Eltern?
  - Nebenjobs verboten
  - Schule zahlt ausreichend Geld für den täglichen Gebrauch

## Charakterbogen
- [x] Welche Informationen sollte der Charakterbogen evtl. Setting-begründet enthalten? z.B. Nationalität; Name des Quirk; besitzt bereits eine Heldenlizenz ja/nein; Entdeckung des Quirk mit welchem Alter; welche Helden-Ausrüstung in Besitz ...
  - erste Seite für Werte
  - zweite Seite mit allgemeinen persönlichen Daten
  - weitere Seiten für weitere Daten / Charakterhintergrund
- [x] Sollte der Charakterbogen eine Inventar-Liste besitzen? Sollte die Helden-Ausrüstung dort aufgeführt und die Funktion der Items charakterindividuell beschrieben sein?
  - Inventarliste als Zusatz ab zweiter Seite, Informationen über Funktionen nur bei Bedarf in Stichpunkten
- [x] Welche menschlichen Talente (Stärke, Wahrnehmung, Gesellschaft etc.) sollen standartmäßig in jedem Charakterbogen vorhanden sein? Nach welchem Prinzip dürfen charakterspezifisch Talente hinzugefügt werden (z.B. 1 pro Rubrik oder insgesamt 3,4,5...)?
  - Talente stehen fest, keine spezifischen möglich
- [x] Wie grob oder fein sollen menschliche Talente definiert sein? z.B. grob: "Wissen" als Wert für alle Wissenstalente - fein: "Astrologie" als Wert innerhalb der Kategorie Wissen
  - Stärke
  - Gewandheit
  - waffenloser Kampf
  - Gadgetnutzung
  - Quirk
  - Wahrnehmung
  - Heimlichkeit
  - Wissen
  - Improvisation (?)
  - z.B. Willenskraft errechnet sich aus anderen Talenten (?)
  - Routineproben situationsabhängig möglich in Quirk und Gadgetnutzung

## Gameplay
- [x] Lebenspunkte (Anzahl; welcher Effekt bei 0 LP? Tod möglich? Ab wann?)
  - errechnet sich aus anderen Talenten (?)
  - Handlungsunfähigkeit / Ohnmacht bei 0 LP
  - Tod nach Meisterentscheid
- [x] Ressource für Fähigkeiten z.B. Quirk-Energie (Anzahl; Drawback bei 0 QE? Welcher Effekt bei Quirk-Nutzung im Drawback?)
  - 30 Ausdauer
  - Ausdauer errechnet sich zu Teilen aus Quirk-Grundstufe
  - unter 0 Ausdauer startet Drawback
  - Drawback-Effekte sind quirkspezifisch
- [x] Kosten von Quirk-Fähigkeiten - auch im Bezug auf das Würfelergebnis
  - Kosten müssen nach eigenem Ermessen sinnvoll bepreist werden und werden später gebalanced
- [x] Schaden von Quirk-Fähigkeiten; Zustände/Zusatzeffekte
  - Schadenswerte sind fix und sollten nach eigenem Ermessen festgelegt werden, der Dummygegner hierfür hat 50LP
  - Startwerte
    - Schaden / Ausdauer verhält sich bei Spontanfertigkeiten 1/1 (10 Schaden / 10 Ausdauer)
    - Konterfertigkeiten zum aktiven verursachen von Schaden verhalten sich 1,5/1 (15 Schaden / 10 Ausdauer)
    - Fähigkeiten mit fixer Castzeit verhalten sich 1,5/1 (15 Schaden / 10 Ausdauer)
    - aufrecht gehaltene Fähigkeiten verhalten sich 1,2/1 (12 Schaden / 10 Ausdauer)
    - Fähigkeiten mit fixer Castzeit, die stattdessen spontan gewirkt werden sollen, verhalten sich 1,5/2 (7,5 Schaden / 10 Ausdauer)
    - Schaden über Zeit verursacht 10 Schaden geteilt durch die Dauer in Kampfrunden (2 Schaden / 5 Kampfrunden)
- [x] Werte für Ausweichen und Parade
  - errechnen sich aus anderen Talenten (?)
- [x] Soll es einen Widerstandswert gegenüber mentalen Quirk-Fähigkeiten geben?
  - vorerst nein
- [x] Nutzen wir einen Geschwindigkeits-Wert?
  - errechnet sich aus anderen Talenten (?)
- [x] Mit welchem Würfel würfeln wir die Initiative?
  - Gewandheitswurf
- [x] Benutzen wir Schicksalspunkte? Wie viele?
  - ja, 1 Schip
  - Wurf gelingt automatisch
- [x] Da wir AP getrennt für menschliche Talente und Quirk-Fähigkeiten erhalten wollen - welche Relation benutzen wir hier? z.B. 1 zu 1 oder 2 zu 1
  - vorerst 1:1, Quirk-Fähigkeiten haben u.a. höhere Kosten als 1 AP
- [x] Zustände?
  - Orientierungslosigkeit (pro Runde)
    -  eine Runde aussetzen
